Lab1
sergey-berezin/441_samarova pull request #3
Opened 2021-11-23 22:32 UTC by s02180519

2021-11-24 06:42 UTC, sergey-berezin requested changes

2021-11-24 06:42 UTC, sergey-berezin commented on Task3(DB)/PictureLibraryContext.cs
> +        public IEnumerable<byte[]> GetPicturesByType(Transfer transfer)
Вместо Transfer можно использовать строку с типом

2021-11-24 06:42 UTC, sergey-berezin commented on WpfTask2Core/MainWindow.xaml.cs
> +                /*byte[] byte_img = Encoding.ASCII.GetBytes(result[i].image);
Все отладочные комментарии нужно убрать

2021-11-24 06:42 UTC, sergey-berezin commented on WpfTask2Core/MainWindow.xaml.cs
> +            for (int i = 0; i < result.Count; i++)
Лучше foreach

2021-12-02 20:47 UTC, s02180519 commented
fix

2021-12-03 08:20 UTC, merged